# Generated by Django 5.2.1 on 2025-05-28 23:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=2)),
                ('api_endpoint', models.URLField()),
                ('api_tipo', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
