# Generated by Django 5.2.1 on 2025-05-30 17:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Parte')),
                ('tipo_parte', models.CharField(choices=[('AUT', 'Autor'), ('REU', 'Réu'), ('LIA', 'Litisconsorte Ativo'), ('LIP', 'Litisconsorte Passivo'), ('ASS', 'Assistente'), ('INE', 'Interveniente')], max_length=3, verbose_name='Tipo de Parte')),
                ('documento', models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
        ),
    ]
