# Generated by Django 5.2.1 on 2025-05-30 17:42

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Movimentação')),
                ('descricao', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descrição da Movimentação')),
                ('observacao', models.TextField(blank=True, max_length=255, null=True, verbose_name='Observação')),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('numero_processo', models.CharField(db_index=True, max_length=26, unique=True, validators=[django.core.validators.RegexValidator(message="Formato inválido. Use '1234567-89.2023.8.26.0100'.", regex='^\\d{7}-\\d{2}\\.\\d{4}\\.\\d\\.\\d{2}\\.\\d{4}$')], verbose_name='Número do Processo')),
                ('tribunal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tribunal')),
                ('classe_processual', models.CharField(blank=True, max_length=100, null=True, verbose_name='Classe Processual')),
                ('assunto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Assunto')),
                ('data_distribuicao', models.DateField(blank=True, null=True, verbose_name='Data de Distribuição')),
                ('orgao_julgador', models.CharField(db_index=True, max_length=100, verbose_name='Órgão Julgador')),
                ('valor_causa', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='Valor da Causa')),
                ('situacao_atual', models.CharField(blank=True, choices=[('CAD', 'Cadastrado'), ('DIS', 'Distribuído'), ('CIT', 'Aguardando Citação'), ('IMP', 'Impulsionado'), ('PRE', 'Em Preparo'), ('PEC', 'Em Pauta para Embargos'), ('REC', 'Recursal'), ('HOM', 'Homologado'), ('SUS', 'Suspenso'), ('AUS', 'Suspenso por Ausência de Partes'), ('PER', 'Suspenso por Perícia'), ('ARQ', 'Arquivado'), ('BAI', 'Baixado'), ('JUL', 'Julgado'), ('EXT', 'Extinto'), ('CUM', 'Cumprido'), ('LIQ', 'Liquidado'), ('DES', 'Desmembrado'), ('INC', 'Incidente Processual'), ('INT', 'Intervenção de Terceiro'), ('UNI', 'Unificado')], default='CAD', max_length=3, null=True, verbose_name='Situação Atual')),
                ('ultima_atualizacao', models.DateTimeField(blank=True, null=True, verbose_name='Última Atualização')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
        ),
    ]
