# Generated by Django 5.2.1 on 2025-05-30 02:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(db_index=True, max_length=26, unique=True, validators=[django.core.validators.RegexValidator(message="Formato inválido. Use '1234567-89.2023.8.26.0100'.", regex='^\\d{7}-\\d{2}\\.\\d{4}\\.\\d\\.\\d{2}\\.\\d{4}$')], verbose_name='Número do Processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
    ]
