# Generated by Django 5.2.1 on 2025-05-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movimentacao',
        ),
    ]
