# Generated by Django 5.2.1 on 2025-05-30 03:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0002_alter_processo_numero_processo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='tribunal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tribunal'),
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Movimentação')),
                ('descricao', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descrição da Movimentação')),
                ('observacao', models.TextField(blank=True, max_length=255, null=True, verbose_name='Observação')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='processo.processo', verbose_name='Processo')),
            ],
        ),
        migrations.DeleteModel(
            name='Tribunal',
        ),
    ]
