# Generated by Django 5.2.1 on 2025-07-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0003_delete_movimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='data_ajuizamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Ajuizamento'),
        ),
        migrations.AddField(
            model_name='processo',
            name='formato',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Formato'),
        ),
        migrations.AddField(
            model_name='processo',
            name='grau',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Grau'),
        ),
        migrations.AddField(
            model_name='processo',
            name='nivel_sigilo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nível de Sigilo'),
        ),
        migrations.AddField(
            model_name='processo',
            name='sistema',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sistema'),
        ),
    ]
