# Generated by Django 5.2.1 on 2025-07-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0004_processo_data_ajuizamento_processo_formato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='formato',
            field=models.CharField(blank=True, choices=[('Físico', 'Físico'), ('Eletrônico', 'Eletrônico'), ('Híbrido', 'Híbrido')], max_length=10, null=True, verbose_name='Formato'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='grau',
            field=models.CharField(blank=True, choices=[('G1', 'G1: Primeiro Grau'), ('G2', 'G2: Segundo Grau'), ('JE', 'JE: Juizado Especial'), ('TU', 'TU: Turma Recursal / Turma Nacional de Uniformização'), ('SG', 'SG: Instância Superior')], max_length=3, null=True, verbose_name='Grau'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='nivel_sigilo',
            field=models.CharField(blank=True, choices=[('Público', 'Público'), ('Restrito', 'Restrito'), ('Sigiloso', 'Sigiloso')], max_length=10, null=True, verbose_name='Nível de Sigilo'),
        ),
    ]
