# Generated by Django 5.2.1 on 2025-07-15 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0005_alter_processo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='processo',
            name='parte_cpf',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="CPF no formato '000.000.000-00'.", regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF da Parte Principal'),
        ),
        migrations.AddField(
            model_name='processo',
            name='parte_nome',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Nome da Parte Principal'),
        ),
    ]
