# Generated by Django 5.2.1 on 2025-05-29 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuariofake_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioFake',
        ),
    ]
