# Adicionar/alterar conforme o necessário

CLASSES = {
    'AC': 'Ação Cautelar',
    'ACP': 'Ação Civil Pública',
    'ADIN': 'Ação Direta de Inconstitucionalidade',
    'AP': 'Ação Penal',
    'APC': 'Apelação Cível',
    'APCr': 'Apelação Criminal',
    'Apl': 'Apelação',
    'AR': 'Agravo Regimental',
    'AI': 'Agravo de Instrumento',
    'AG': 'Agravo',
    'HC': 'Habeas Corpus',
    'MS': 'Mandado de Segurança',
    'RE': 'Recurso Extraordinário',
    'REs': 'Recurso Especial',
    'RO': 'Recurso Ordinário',
    'RT': 'Recurso Trabalhista',
    'RTOrd': 'Recurso Ordinário Trabalhista',
    'RTSum': 'Recurso Sumário Trabalhista',
    'RTD': 'Recurso de Revista Trabalhista',
    'Rcl': 'Reclamação',
    'RclTr': 'Reclamação Trabalhista',
    'REx': 'Recurso Extraordinário',
    'RSE': 'Recurso em Sentido Estrito',
    'ST': 'Sentença',
    'TP': 'Tutela Provisória',
    'TPA': 'Tutela Provisória Antecipada',
    'TPU': 'Tutela Provisória de Urgência',
    'TPe': 'Tutela Provisória de Evidência',
    'MS': 'Mandado de Segurança',
    'MSCol': 'Mandado de Segurança Coletivo',
    'MSI': 'Mandado de Segurança Individual',
    'OUTROS': 'Outros',
}

MOVIMENTOS = {
    '1': 'Distribuição',
    '2': 'Remessa',
    '3': 'Baixa/Arquivo',
    '11': 'Juntada de Petição',
    '22': 'Conclusão',
    '26': 'Audiência',
    '51': 'Sentença',
    '60': 'Trânsito em Julgado',
    '123': 'Decisão',
    '132': 'Citação',
    '193': 'Recurso',
    '246': 'Execução',
}

FORMATOS = {
    'PDF': 'Documento PDF',
    'DOC': 'Documento Word',
    'DOCX': 'Documento Word (Novo)',
    'XLS': 'Planilha Excel',
    'XLSX': 'Planilha Excel (Novo)',
    'TXT': 'Documento de Texto',
    'JPG': 'Imagem JPEG',
    'PNG': 'Imagem PNG',
}